[workspace]
members = [
    "resplatted",
    "resplatted-protocol"
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["ht06"]

[workspace.dependencies]
# Internal crates
resplatted-protocol = { path = "resplatted-protocol" }

# External dependencies
tokio = { version = "1.52.3", features = ["net", "io-util"] }

# log
log = "0.4.29"
simplelog = "0.12.2"
bytes = "1.11.1"
