[package]
name = "resplatted"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
resplatted-protocol.workspace = true
clap = { version = "4", features = ["derive"] }

# Log
log.workspace = true
simplelog.workspace = true

#tokio
tokio.workspace = true
tokio-util = "0.7.18" # Cancellation Token

text_components.workspace = true

#serde
serde_json = "1.0.150"

# base 64 used for the favicon
base64 = "0.22.1"

# flate for packet compression
flate2 = "1.1.9"

# Color the motd when fetching the status
colored = "3.1.1"

rand.workspace = true

# Bench
criterion = { version = "0.8.2", features = ["async_tokio"] }

[[bench]]
name = "packet_decompression"
harness = false
