[package]
name = "resplatted-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
uuid = { version = "1.23.1", features = ["v4"] }
# rand.workspace = true # remove the comment when using rand for the chat message packet
fastnbt = "2.6.1"
serde = "1.0.228"
